image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Code Linting
            script:
              - npm install -g eslint
              # - npx eslint .
            caches:
              - node
